### PR TITLE
use keccak_ex

### PR DESCRIPTION
**Pull request by N-0x90**
Replace NIF with Elixir implementation of Keccak 256.

### CODE REVIEW

**Comment by syfgkjasdkn** [comment]
Hi @N-0x90, could you please provide a bit more reasoning for the change? I'd rather keep using the nif.

**Comment by N-0x90** [comment]
Some times when change over win, os, linux... have some hard time to compile the NIF... can add code to chose by config use nif or ex...

**Comment by syfgkjasdkn** [comment]
@N-0x90 ok, I'll add an optional config key for providing the module for hashing.

**Comment by syfgkjasdkn** [comment]
https://github.com/syfgkjasdkn/tron-protocol/issues/2

**Pull request closed without merging**
